# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ayman/.jetbrains/clion-2018.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ayman/.jetbrains/clion-2018.2.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayman/Projects/ezserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayman/Projects/ezserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ayman/.jetbrains/clion-2018.2.4/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ayman/.jetbrains/clion-2018.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayman/Projects/ezserver/CMakeFiles /home/ayman/Projects/ezserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayman/Projects/ezserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ezserver

# Build rule for target.
ezserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ezserver
.PHONY : ezserver

# fast build rule for target.
ezserver/fast:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/build
.PHONY : ezserver/fast

src/application.o: src/application.cc.o

.PHONY : src/application.o

# target to build an object file
src/application.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/application.cc.o
.PHONY : src/application.cc.o

src/application.i: src/application.cc.i

.PHONY : src/application.i

# target to preprocess a source file
src/application.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/application.cc.i
.PHONY : src/application.cc.i

src/application.s: src/application.cc.s

.PHONY : src/application.s

# target to generate assembly for a file
src/application.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/application.cc.s
.PHONY : src/application.cc.s

src/bootstrapper.o: src/bootstrapper.cc.o

.PHONY : src/bootstrapper.o

# target to build an object file
src/bootstrapper.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/bootstrapper.cc.o
.PHONY : src/bootstrapper.cc.o

src/bootstrapper.i: src/bootstrapper.cc.i

.PHONY : src/bootstrapper.i

# target to preprocess a source file
src/bootstrapper.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/bootstrapper.cc.i
.PHONY : src/bootstrapper.cc.i

src/bootstrapper.s: src/bootstrapper.cc.s

.PHONY : src/bootstrapper.s

# target to generate assembly for a file
src/bootstrapper.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/bootstrapper.cc.s
.PHONY : src/bootstrapper.cc.s

src/config/configuration.o: src/config/configuration.cc.o

.PHONY : src/config/configuration.o

# target to build an object file
src/config/configuration.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/config/configuration.cc.o
.PHONY : src/config/configuration.cc.o

src/config/configuration.i: src/config/configuration.cc.i

.PHONY : src/config/configuration.i

# target to preprocess a source file
src/config/configuration.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/config/configuration.cc.i
.PHONY : src/config/configuration.cc.i

src/config/configuration.s: src/config/configuration.cc.s

.PHONY : src/config/configuration.s

# target to generate assembly for a file
src/config/configuration.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/config/configuration.cc.s
.PHONY : src/config/configuration.cc.s

src/introp/plugins_loader.o: src/introp/plugins_loader.cc.o

.PHONY : src/introp/plugins_loader.o

# target to build an object file
src/introp/plugins_loader.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/introp/plugins_loader.cc.o
.PHONY : src/introp/plugins_loader.cc.o

src/introp/plugins_loader.i: src/introp/plugins_loader.cc.i

.PHONY : src/introp/plugins_loader.i

# target to preprocess a source file
src/introp/plugins_loader.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/introp/plugins_loader.cc.i
.PHONY : src/introp/plugins_loader.cc.i

src/introp/plugins_loader.s: src/introp/plugins_loader.cc.s

.PHONY : src/introp/plugins_loader.s

# target to generate assembly for a file
src/introp/plugins_loader.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/introp/plugins_loader.cc.s
.PHONY : src/introp/plugins_loader.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/net/async_tcp_client.o: src/net/async_tcp_client.cc.o

.PHONY : src/net/async_tcp_client.o

# target to build an object file
src/net/async_tcp_client.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/net/async_tcp_client.cc.o
.PHONY : src/net/async_tcp_client.cc.o

src/net/async_tcp_client.i: src/net/async_tcp_client.cc.i

.PHONY : src/net/async_tcp_client.i

# target to preprocess a source file
src/net/async_tcp_client.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/net/async_tcp_client.cc.i
.PHONY : src/net/async_tcp_client.cc.i

src/net/async_tcp_client.s: src/net/async_tcp_client.cc.s

.PHONY : src/net/async_tcp_client.s

# target to generate assembly for a file
src/net/async_tcp_client.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/net/async_tcp_client.cc.s
.PHONY : src/net/async_tcp_client.cc.s

src/net/async_tcp_listener.o: src/net/async_tcp_listener.cc.o

.PHONY : src/net/async_tcp_listener.o

# target to build an object file
src/net/async_tcp_listener.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/net/async_tcp_listener.cc.o
.PHONY : src/net/async_tcp_listener.cc.o

src/net/async_tcp_listener.i: src/net/async_tcp_listener.cc.i

.PHONY : src/net/async_tcp_listener.i

# target to preprocess a source file
src/net/async_tcp_listener.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/net/async_tcp_listener.cc.i
.PHONY : src/net/async_tcp_listener.cc.i

src/net/async_tcp_listener.s: src/net/async_tcp_listener.cc.s

.PHONY : src/net/async_tcp_listener.s

# target to generate assembly for a file
src/net/async_tcp_listener.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/net/async_tcp_listener.cc.s
.PHONY : src/net/async_tcp_listener.cc.s

src/services/console_logger.o: src/services/console_logger.cc.o

.PHONY : src/services/console_logger.o

# target to build an object file
src/services/console_logger.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/console_logger.cc.o
.PHONY : src/services/console_logger.cc.o

src/services/console_logger.i: src/services/console_logger.cc.i

.PHONY : src/services/console_logger.i

# target to preprocess a source file
src/services/console_logger.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/console_logger.cc.i
.PHONY : src/services/console_logger.cc.i

src/services/console_logger.s: src/services/console_logger.cc.s

.PHONY : src/services/console_logger.s

# target to generate assembly for a file
src/services/console_logger.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/console_logger.cc.s
.PHONY : src/services/console_logger.cc.s

src/services/filesystem.o: src/services/filesystem.cc.o

.PHONY : src/services/filesystem.o

# target to build an object file
src/services/filesystem.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/filesystem.cc.o
.PHONY : src/services/filesystem.cc.o

src/services/filesystem.i: src/services/filesystem.cc.i

.PHONY : src/services/filesystem.i

# target to preprocess a source file
src/services/filesystem.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/filesystem.cc.i
.PHONY : src/services/filesystem.cc.i

src/services/filesystem.s: src/services/filesystem.cc.s

.PHONY : src/services/filesystem.s

# target to generate assembly for a file
src/services/filesystem.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/filesystem.cc.s
.PHONY : src/services/filesystem.cc.s

src/services/services_manager.o: src/services/services_manager.cc.o

.PHONY : src/services/services_manager.o

# target to build an object file
src/services/services_manager.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/services_manager.cc.o
.PHONY : src/services/services_manager.cc.o

src/services/services_manager.i: src/services/services_manager.cc.i

.PHONY : src/services/services_manager.i

# target to preprocess a source file
src/services/services_manager.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/services_manager.cc.i
.PHONY : src/services/services_manager.cc.i

src/services/services_manager.s: src/services/services_manager.cc.s

.PHONY : src/services/services_manager.s

# target to generate assembly for a file
src/services/services_manager.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/services/services_manager.cc.s
.PHONY : src/services/services_manager.cc.s

src/utils/time.o: src/utils/time.cc.o

.PHONY : src/utils/time.o

# target to build an object file
src/utils/time.cc.o:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/utils/time.cc.o
.PHONY : src/utils/time.cc.o

src/utils/time.i: src/utils/time.cc.i

.PHONY : src/utils/time.i

# target to preprocess a source file
src/utils/time.cc.i:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/utils/time.cc.i
.PHONY : src/utils/time.cc.i

src/utils/time.s: src/utils/time.cc.s

.PHONY : src/utils/time.s

# target to generate assembly for a file
src/utils/time.cc.s:
	$(MAKE) -f CMakeFiles/ezserver.dir/build.make CMakeFiles/ezserver.dir/src/utils/time.cc.s
.PHONY : src/utils/time.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ezserver"
	@echo "... src/application.o"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/bootstrapper.o"
	@echo "... src/bootstrapper.i"
	@echo "... src/bootstrapper.s"
	@echo "... src/config/configuration.o"
	@echo "... src/config/configuration.i"
	@echo "... src/config/configuration.s"
	@echo "... src/introp/plugins_loader.o"
	@echo "... src/introp/plugins_loader.i"
	@echo "... src/introp/plugins_loader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/async_tcp_client.o"
	@echo "... src/net/async_tcp_client.i"
	@echo "... src/net/async_tcp_client.s"
	@echo "... src/net/async_tcp_listener.o"
	@echo "... src/net/async_tcp_listener.i"
	@echo "... src/net/async_tcp_listener.s"
	@echo "... src/services/console_logger.o"
	@echo "... src/services/console_logger.i"
	@echo "... src/services/console_logger.s"
	@echo "... src/services/filesystem.o"
	@echo "... src/services/filesystem.i"
	@echo "... src/services/filesystem.s"
	@echo "... src/services/services_manager.o"
	@echo "... src/services/services_manager.i"
	@echo "... src/services/services_manager.s"
	@echo "... src/utils/time.o"
	@echo "... src/utils/time.i"
	@echo "... src/utils/time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

